# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build_test_docker:
    docker:
      - image: circleci/golang:1.11.6
      
    working_directory: ~/go/src/github.com/iotexproject/iotex-antenna-go
    #environment:
    #  - GOPATH: "${HOME}/go"

    steps:
      - checkout

      - run: 
          name: go test
          command: |
            export GOPATH=~/go
            set -e 
            for d in $(go list ./...); do
              go test -short -v -coverprofile=profile.out -covermode=count "$d"
              if [ -f profile.out ]; then
                cat profile.out >> coverage.txt
                rm profile.out
              fi
            done
          
workflows:
  version: 2
  commit:
    jobs:
      - build_test_docker
